SELECT * FROM MARK WHERE MARK>6 ORDER BY MARK DESC;
SELECT * FROM PAYMENT WHERE AMOUNT <300 ORDER BY AMOUNT ASC;
SELECT * FROM PAYMENTTYPE ORDER BY PAYMENTTYPE.NAME ASC;
SELECT * FROM STUDENT ORDER BY STUDENT.NAME DESC;
SELECT DISTINCT s.id, s.name, s.birthday, s.groupnumber FROM student AS s JOIN payment AS p ON s.id = p.student_id WHERE p.amount > 1000 ORDER BY s.birthday;
