SELECT max(BIRTHDAY) from STUDENT;
SELECT min(PAYMENT_DATE) from PAYMENT;
SELECT avg(MARK) from MARK as M JOIN SUBJECT AS S ON M.SUBJECT_ID = S.ID WHERE S.NAME = 'Math';
SELECT min(p.AMOUNT) FROM PAYMENT AS P JOIN PAYMENTTYPE AS T ON P.TYPE_ID = T.ID WHERE T.NAME = 'WEEKLY';